spring:
  application:
    name: dispatcher-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      username: user
      password: password
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          [
            health,
            prometheus,
            info,
            env,
            functions,
            heapdump,
            info,
            loggers,
            mappings,
            configprops,
            bindings,
          ]
  metrics:
    tags:
      application: ${spring.application.name}
